pull_request_rules:
- name: Automatically merge Scala Steward PRs
  conditions:
  - author=horothesun-scala-steward[bot]
  - "#approved-reviews-by>=1"
  - status-success=Build, test and push
  actions:
    merge:
      method: squash
