name: Manual API call

on:
  workflow_dispatch: # enable manual execution

env:
  PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}

jobs:
  manual-api-call:
    name: Manual API call
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: API call
      run: |
        curl --silent \
          --write-out "\n%{http_code}\n" \
          --request "GET" "${PROD_BASE_URL}/time" | \
          jq --slurp '{ http_code: .[1], response: .[0] }'
